// SPDX-License-Identifier: Apache-2.0
#define NO_SYS 1
#define SYS_LIGHTWEIGHT_PROT 0
#define LWIP_SOCKET 0
#define LWIP_NETCONN 0
#define LWIP_TIMERS 0
#define LWIP_IPV4 1
#define LWIP_IPV6 0
#define LWIP_ARP 0
#define LWIP_ETHERNET 0
#define LWIP_ICMP 0
#define LWIP_UDP 0
#define LWIP_RAW 0
#define LWIP_TCP 1
#define LWIP_HAVE_LOOPIF 1
#define LWIP_NETIF_LOOPBACK 1
#define TCP_MSS 1440
#define TCP_WND 2880
#define TCP_SND_BUF 2880
#define MEM_ALIGNMENT 8
#define MEM_SIZE 65536
#define MEMP_NUM_TCP_PCB 8
#define MEMP_NUM_TCP_SEG 64
#define LWIP_HOOK_FILENAME "packet_observer.h"
